//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_ID { get; set; }
        public int Schedule_ID { get; set; }
        public int Person_ID { get; set; }
        public string Item_Name { get; set; }
        public string Item_Description { get; set; }
        public int Item_Quantity { get; set; }
        public string Customer_Name { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
